info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'

logging:
  level:
    org:
      apache:
        http: INFO
    nl:
      bsoft: DEBUG
    web: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
    git:
      mode: full
      enabled: true
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: '*'
        exclude:

nl:
  bsoft:
    ihr:
      library:
        config:
          ihr:
            rest:
              api:
                maxpagesize: 100
                baseurl: https://ruimte.omgevingswet.overheid.nl/ruimtelijke-plannen/api/opvragen/v4
                apikey: l7f833bd256c04444da04b0fe9ad3def88
                coordinatereferencesystem: epsg:28992


server:
  port: 8080

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ihr
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/ihr
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: true
        jdbc:
          batch_size: 100
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
#    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect